### ISSUE TITLE
Unable to start engine from Web UI

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#448]
I've had a report where the Web UI is unable to start the engine; and so the webui is stuck on the "starting pipeline 2 engine" page. Here's some relevant portions from the log file:

```
Database:
  deployment: desktop
  dp2ws.endpoint: http://localhost:8181/ws
  dp2ws.authid: 
  dp2ws.secret: [hidden]
application.conf and system variables:
  sun.management.compiler: HotSpot Client Compiler
  sun.cpu.endian: little
  java.specification.version: 1.8
  java.vm.specification.name: Java Virtual Machine Specification
  java.vm.specification.version: 1.8
  file.encoding.pkg: sun.io
  sun.arch.data.model: 32
  sun.boot.library.path: C:\Program Files\Java\jre1.8.0_25\bin
  user.dir: C:\Program Files\DAISY Pipeline 2\daisy-pipeline\webui
  sun.cpu.isalist: pentium_pro+mmx pentium_pro pentium+mmx pentium i486 i386 i86
  sun.desktop: windows
  os.arch: x86
  java.vm.version: 25.25-b02
  java.endorsed.dirs: C:\Program Files\Java\jre1.8.0_25\lib\endorsed
  java.runtime.version: 1.8.0_25-b18
  java.runtime.name: Java(TM) SE Runtime Environment
  java.class.version: 52.0
  java.specification.name: Java Platform API Specification
  version: 1.8.1
  java.specification.vendor: Oracle Corporation
  sun.java.launcher: SUN_STANDARD
  os.version: 5.1
  sun.os.patch.level: Service Pack 2
  java.vm.specification.vendor: Oracle Corporation
  sun.jnu.encoding: Cp1252
  awt.toolkit: sun.awt.windows.WToolkit
  os.name: Windows XP
  java.vm.vendor: Oracle Corporation
  java.vm.name: Java HotSpot(TM) Client VM
  java.version: 1.8.0_25
  sun.io.unicode.encoding: UnicodeLittle
```

Some exceptions from the engine in the log:

```
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] load script XProcScript[name=Nordic EPUB3 Validator]   @o.d.p.p.i.job.PersistentJobContext:207#setScriptUri
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] load script XProcScript[name=Nordic EPUB3 Validator]   @o.d.p.p.i.job.PersistentJobContext:207#setScriptUri
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] Post loading jobcontext   @o.d.p.p.i.job.PersistentJobContext:119#postLoad
DEBUG [ org.eclipse.persistence.logging.default] Connection(25195114)--Thread(Thread[qtp18210293-55,5,Configuration Admin Service])--SELECT jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp FROM PERSISTENTMESSAGE WHERE ((jobId = ?) AND (sequence > ?))
 bind => [2 parameters bound]   @o.d.p.p.logging.Slf4jSessionLogger:108#log
Jan 30, 2015 10:03:55 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2015-01-30 10:03:55    127.0.0.1   -   127.0.0.1   8181    GET /ws/jobs/2c80b629-d9fe-4eea-96e0-9f7d43c4c543   msgSeq=305& 200 -   0   31  http://localhost:8181   Apache-HttpClient/4.1.3 (java 1.5)  -
DEBUG [o.a.h.i.c.PoolingClientConnectionManager] Connection manager is shutting down   @o.a.h.i.c.PoolingClientConnectionManager:287#shutdown
DEBUG [o.a.h.i.c.PoolingClientConnectionManager] Connection manager shut down   @o.a.h.i.c.PoolingClientConnectionManager:293#shutdown
Exception in thread "Thread-31" java.lang.StackOverflowError
 at net.sf.saxon.regex.BMPString.isEnd(BMPString.java:54)
 at net.sf.saxon.regex.Operation$OpCharClass.exec(Operation.java:721)
 at net.sf.saxon.regex.REMatcher.matchNodes(REMatcher.java:413)
 at net.sf.saxon.regex.Operation$OpStar.exec(Operation.java:235)
 at net.sf.saxon.regex.REMatcher.matchNodes(REMatcher.java:413)
 at net.sf.saxon.regex.Operation$OpStar.exec(Operation.java:235)
 at net.sf.saxon.regex.REMatcher.matchNodes(REMatcher.java:413)
 at net.sf.saxon.regex.Operation$OpStar.exec(Operation.java:235)
 at net.sf.saxon.regex.REMatcher.matchNodes(REMatcher.java:413)
(repeats ~1000 times)
 at net.sf.saxon.regex.REMatcher.matchNodes(REMatcher.java:413)
 at net.sf.saxon.regex.Operation$OpStar.exec(Operation.java:235)
DEBUG [ org.eclipse.persistence.logging.default] Connection(31957303)--Thread(Thread[qtp18210293-55,5,Configuration Admin Service])--SELECT job_id, PRIORITY, STATUS, CONTEXT_job_id FROM jobs WHERE (job_id = ?)
 bind => [1 parameter bound]   @o.d.p.p.logging.Slf4jSessionLogger:108#log
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] load script XProcScript[name=Nordic EPUB3 Validator]   @o.d.p.p.i.job.PersistentJobContext:207#setScriptUri
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] load script XProcScript[name=Nordic EPUB3 Validator]   @o.d.p.p.i.job.PersistentJobContext:207#setScriptUri
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] Post loading jobcontext   @o.d.p.p.i.job.PersistentJobContext:119#postLoad
DEBUG [ org.eclipse.persistence.logging.default] Connection(25899663)--Thread(Thread[qtp18210293-55,5,Configuration Admin Service])--SELECT jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp FROM PERSISTENTMESSAGE WHERE ((jobId = ?) AND (sequence > ?))
 bind => [2 parameters bound]   @o.d.p.p.logging.Slf4jSessionLogger:108#log
Jan 30, 2015 10:03:56 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2015-01-30 10:03:56    127.0.0.1   -   127.0.0.1   8181    GET /ws/jobs/2c80b629-d9fe-4eea-96e0-9f7d43c4c543   msgSeq=305& 200 -   0   15  http://localhost:8181   Apache-HttpClient/4.1.3 (java 1.5)  -
Jan 30, 2015 10:03:57 AM org.restlet.resource.ServerResource doCatch
WARNING: Exception or error caught in server resource
Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
 at org.restlet.resource.ServerResource.doHandle(ServerResource.java:517)
 at org.restlet.resource.ServerResource.get(ServerResource.java:707)
 at org.restlet.resource.ServerResource.doHandle(ServerResource.java:589)
 at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:649)
 at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:348)
 at org.restlet.resource.ServerResource.handle(ServerResource.java:951)
 at org.restlet.resource.Finder.handle(Finder.java:246)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Router.doHandle(Router.java:431)
 at org.restlet.routing.Router.handle(Router.java:648)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
 at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:84)
 at org.restlet.Application.handle(Application.java:381)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Router.doHandle(Router.java:431)
 at org.restlet.routing.Router.handle(Router.java:648)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Router.doHandle(Router.java:431)
 at org.restlet.routing.Router.handle(Router.java:648)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
 at org.restlet.Component.handle(Component.java:392)
 at org.restlet.Server.handle(Server.java:516)
 at org.restlet.engine.ServerHelper.handle(ServerHelper.java:72)
 at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:152)
 at org.restlet.ext.jetty.JettyServerHelper$WrappedServer.handle(JettyServerHelper.java:170)
 at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
 at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:884)
 at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:938)
 at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630)
 at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
 at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
 at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:622)
 at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
 at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
 at org.daisy.pipeline.webserviceutils.xml.JobXmlWriter.addElementData(JobXmlWriter.java:125)
 at org.daisy.pipeline.webserviceutils.xml.JobXmlWriter.addAsElementChild(JobXmlWriter.java:54)
 at org.daisy.pipeline.webserviceutils.xml.JobsXmlWriter.jobsToXml(JobsXmlWriter.java:43)
 at org.daisy.pipeline.webserviceutils.xml.JobsXmlWriter.getXmlDocument(JobsXmlWriter.java:27)
 at org.daisy.pipeline.webservice.impl.JobsResource.getResource(JobsResource.java:95)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at org.restlet.resource.ServerResource.doHandle(ServerResource.java:506)
 ... 52 more

Jan 30, 2015 10:03:57 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2015-01-30 10:03:57    127.0.0.1   -   127.0.0.1   8181    GET /ws/jobs    -   500 -   0   16  http://localhost:8181   Apache-HttpClient/4.1.3 (java 1.5)  -
```

```
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] load script XProcScript[name=Nordic EPUB3 Validator]   @o.d.p.p.i.job.PersistentJobContext:207#setScriptUri
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] load script XProcScript[name=Nordic EPUB3 Validator]   @o.d.p.p.i.job.PersistentJobContext:207#setScriptUri
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] Post loading jobcontext   @o.d.p.p.i.job.PersistentJobContext:119#postLoad
DEBUG [ org.eclipse.persistence.logging.default] Connection(8913091)--Thread(Thread[qtp18210293-40,5,Configuration Admin Service])--SELECT jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp FROM PERSISTENTMESSAGE WHERE ((jobId = ?) AND (sequence > ?))
 bind => [2 parameters bound]   @o.d.p.p.logging.Slf4jSessionLogger:108#log
Jan 30, 2015 10:11:21 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2015-01-30 10:11:21    127.0.0.1   -   127.0.0.1   8181    GET /ws/jobs/cd031eb2-3e1c-44fb-a09d-39dbbaf35fa2   msgSeq=305& 200 -   0   16  http://localhost:8181   Apache-HttpClient/4.1.3 (java 1.5)  -
DEBUG [o.a.h.i.c.PoolingClientConnectionManager] Connection manager is shutting down   @o.a.h.i.c.PoolingClientConnectionManager:287#shutdown
DEBUG [o.a.h.i.c.PoolingClientConnectionManager] Connection manager shut down   @o.a.h.i.c.PoolingClientConnectionManager:293#shutdown
Exception in thread "Thread-40" java.lang.StackOverflowError
 at net.sf.saxon.z.IntHashMap.put(IntHashMap.java:146)
 at net.sf.saxon.regex.REMatcher.beenHereBefore(REMatcher.java:464)
 at net.sf.saxon.regex.Operation$OpStar.exec(Operation.java:228)
 at net.sf.saxon.regex.REMatcher.matchNodes(REMatcher.java:413)
 at net.sf.saxon.regex.Operation$OpStar.exec(Operation.java:235)
 at net.sf.saxon.regex.REMatcher.matchNodes(REMatcher.java:413)
 at net.sf.saxon.regex.Operation$OpStar.exec(Operation.java:235)
 at net.sf.saxon.regex.REMatcher.matchNodes(REMatcher.java:413)
(repeats ~1000 times)
 at net.sf.saxon.regex.Operation$OpStar.exec(Operation.java:235)
 at net.sf.saxon.regex.REMatcher.matchNodes(REMatcher.java:413)
```

```
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] load script XProcScript[name=Nordic EPUB3 Validator]   @o.d.p.p.i.job.PersistentJobContext:207#setScriptUri
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] load script XProcScript[name=Nordic EPUB3 Validator]   @o.d.p.p.i.job.PersistentJobContext:207#setScriptUri
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] Post loading jobcontext   @o.d.p.p.i.job.PersistentJobContext:119#postLoad
DEBUG [ org.eclipse.persistence.logging.default] Connection(27766924)--Thread(Thread[qtp18210293-72,5,Configuration Admin Service])--SELECT jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp FROM PERSISTENTMESSAGE WHERE ((jobId = ?) AND (sequence > ?))
 bind => [2 parameters bound]   @o.d.p.p.logging.Slf4jSessionLogger:108#log
Jan 30, 2015 10:19:03 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2015-01-30 10:19:03    127.0.0.1   -   127.0.0.1   8181    GET /ws/jobs/2c80b629-d9fe-4eea-96e0-9f7d43c4c543   msgSeq=305& 200 -   0   15  http://localhost:8181   Apache-HttpClient/4.1.3 (java 1.5)  -
DEBUG [ org.eclipse.persistence.logging.default] Connection(21716071)--Thread(Thread[qtp18210293-73,5,Configuration Admin Service])--SELECT job_id, PRIORITY, STATUS, CONTEXT_job_id FROM jobs   @o.d.p.p.logging.Slf4jSessionLogger:108#log
INFO  [      o.d.p.w.impl.PipelineStatusService] Error caught from application(resource): Internal Server Error   @o.d.p.w.impl.PipelineStatusService:45#getStatus
INFO  [      o.d.p.w.impl.PipelineStatusService] Overriding error representation: Internal Server Error   @o.d.p.w.impl.PipelineStatusService:24#getRepresentation
Jan 30, 2015 10:19:03 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2015-01-30 10:19:03    127.0.0.1   -   127.0.0.1   8181    GET /ws/alive   -   200 -   0   0   http://localhost:8181   Apache-HttpClient/4.1.3 (java 1.5)  -
Jan 30, 2015 10:19:03 AM org.restlet.resource.ServerResource doCatch
WARNING: Exception or error caught in server resource
Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
 at org.restlet.resource.ServerResource.doHandle(ServerResource.java:517)
 at org.restlet.resource.ServerResource.get(ServerResource.java:707)
 at org.restlet.resource.ServerResource.doHandle(ServerResource.java:589)
 at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:649)
 at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:348)
 at org.restlet.resource.ServerResource.handle(ServerResource.java:951)
 at org.restlet.resource.Finder.handle(Finder.java:246)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Router.doHandle(Router.java:431)
 at org.restlet.routing.Router.handle(Router.java:648)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
 at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:84)
 at org.restlet.Application.handle(Application.java:381)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Router.doHandle(Router.java:431)
 at org.restlet.routing.Router.handle(Router.java:648)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Router.doHandle(Router.java:431)
 at org.restlet.routing.Router.handle(Router.java:648)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.routing.Filter.doHandle(Filter.java:159)
 at org.restlet.routing.Filter.handle(Filter.java:206)
 at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
 at org.restlet.Component.handle(Component.java:392)
 at org.restlet.Server.handle(Server.java:516)
 at org.restlet.engine.ServerHelper.handle(ServerHelper.java:72)
 at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:152)
 at org.restlet.ext.jetty.JettyServerHelper$WrappedServer.handle(JettyServerHelper.java:170)
 at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
 at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:884)
 at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:938)
 at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630)
 at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
 at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
 at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:622)
 at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
 at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
 at org.daisy.pipeline.webserviceutils.xml.JobXmlWriter.addElementData(JobXmlWriter.java:125)
 at org.daisy.pipeline.webserviceutils.xml.JobXmlWriter.addAsElementChild(JobXmlWriter.java:54)
 at org.daisy.pipeline.webserviceutils.xml.JobsXmlWriter.jobsToXml(JobsXmlWriter.java:43)
 at org.daisy.pipeline.webserviceutils.xml.JobsXmlWriter.getXmlDocument(JobsXmlWriter.java:27)
 at org.daisy.pipeline.webservice.impl.JobsResource.getResource(JobsResource.java:95)
 at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at org.restlet.resource.ServerResource.doHandle(ServerResource.java:506)
 ... 52 more

Jan 30, 2015 10:19:03 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2015-01-30 10:19:03    127.0.0.1   -   127.0.0.1   8181    GET /ws/jobs    -   500 -   0   15  http://localhost:8181   Apache-HttpClient/4.1.3 (java 1.5)  -
```

**Comment by capitancambio** [comment]
I don't really know why the engine is not starting... maybe a lingering
pipeline that wasn't shutdown?

The errors in the log are a bit interesting. There seems to be a problem
with one of the regexps, and then a null pointer exception while accessing
a job, not sure what to say really, this never happened before. Can I have
the books this user was using?

cheers,

Javi

**Comment by josteinaj** [comment]
> I don't really know why the engine is not starting... maybe a lingering pipeline that wasn't shutdown?

Yeah, that's what I'm thinking as well, but apparently restarting DP2 or rebooting doesn't help. I'm not sure if these exceptions are related to this issue or not though.

> There seems to be a problem with one of the regexps

Indeed. And I'm guessing it's an issue with the nordic scripts, but I'm not sure. Would be great to have a way of locating which regexp has this issue. Maybe with a book to reproduce it we could.

> Can I have the books this user was using?

I'll try to obtain it.

**Comment by capitancambio** [comment]
:+1: Thanks!

cheers,

Javi

**Comment by josteinaj** [comment]
I'm wondering if we should just close this one as we won't have a desktop mode in the next version of the webui (in case that's the source of the problem), and the affected modules will also have been updated by then. wdyt?

**Comment by bertfrees** [comment]
@josteinaj Is this still relevant?

**Comment by josteinaj** [comment]
No. Let's close it.
