### ISSUE TITLE
NoClassDefFoundError: javafx/application/Application

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#482]
According to [an answer on StackOverflow](http://stackoverflow.com/a/18344096/281065), "it appears that you MUST use one of the JavaFX packaging tools, which is either an Ant task or the javafxpackager executable". Not sure if that's the issue here though, but it's the first hit on google when searching for the exception.

Output from v1.10 beta1:

```
➜  bin ./pipeline2 gui
(...)
Exception in thread "Thread-13" java.lang.NoClassDefFoundError: javafx/application/Application
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2318)
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1524)
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.daisy.pipeline.gui.GUIService$1.run(GUIService.java:24)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.apache.felix.framework.ExtensionManager$ExtensionManagerWiring.getClassByDelegation(ExtensionManager.java:881)
    at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1577)
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1507)
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 8 more
```

**Comment by bertfrees** [comment]
Any idea where we can find the code of these generated classes?

**Comment by bertfrees** [comment]
@marisademeglio Probably unrelated, but I'm wondering: Why did we have our custom launcher but [later deleted that](https://github.com/daisy/pipeline-assembly/commit/29f45551a10341adede9a1779ba1073a9029838e)?

**Comment by rdeltour** [comment]
> "it appears that you MUST use one of the JavaFX packaging tools, which is either an Ant task or the javafxpackager executable"

I don't think that's the case. We do use it for the macOS package, but we're not using it on Windows and the GUI runs fine there.

**Comment by rdeltour** [comment]
I think this is no longer an issue. @bertfrees or @josteinaj can you confirm so that I can close the old `v1.10.0` milestone?

**Comment by bertfrees** [comment]
Hmm, I thought the issue was that Jostein was using openjdk which does not have JavaFX by default.

**Comment by josteinaj** [comment]
I tried in a clean Ubuntu 16.10 VM now, installing `default-jre` (OpenJDK 8), and I get the same exception as above. However, this is output first:

```
$ bin/pipeline2 gui
pipeline2: JAVA_HOME not set; results may vary
pipeline2: Your version of Java possibly does not support JavaFX, which is required to start the GUI. See http://daisy.github.io/pipeline/Get-Help/User-Guide/Installation/#javafx for more information.
Will continue in 10s. Hit ^C to abort, or ENTER to continue now.
(...)
```

So the user is given a warning.

If I enable the universe repository in Ubuntu, I can install JavaFX with `sudo apt install openjfx`.

After that, I still get the same warning at the beginning, but the GUI appears as it should.

So I guess this issue can be closed. It would also be good to add a note to the installation instructions about the `openjfx` package in Ubuntus universe repo.

**Comment by bertfrees** [comment]
Is there a difference between the package in the universe repository and the package in Debian stable?

**Comment by bertfrees** [comment]
The Debian tracker page also has a link to the Ubuntu page.

**Comment by josteinaj** [comment]
I don't know.

**Comment by marisademeglio** [comment]
@bertfrees I don't know for sure about the custom launcher disappearing but my best guess is that it was originally done with some special parameters required for javafx (runOnFirstThread or something...it's been years since I've thought about this). Maybe the underlying architecture changed so that a special launcher wasn't required?  @capitancambio might know (sorry javi!)
