### ISSUE TITLE
pipeline2 1.10.2 seems to throw a sql error while converting a document

### ISSUE THREAD

**Issue by rkeiii** [daisy/pipeline#517]
I am seeing this error after submitting a document for conversion to EPUB3. Any idea what might be causing this?

```
INFO   [     com.xmlcalabash.runtime.XAtomicStep] bundle://108.0:1/xml/dtbook2005-3-to-zedai.xpl:226:44:Normalize mixed section and block content model for level1   @o.d.c.x.c.i.slf4jXProcMessageListener:80#info
INFO   [     com.xmlcalabash.runtime.XAtomicStep] bundle://108.0:1/xml/dtbook2005-3-to-zedai.xpl:226:44:Normalize mixed section and block content model for level1   @o.d.c.x.c.i.slf4jXProcMessageListener:80#info
INFO   [     com.xmlcalabash.runtime.XAtomicStep] bundle://108.0:1/xml/dtbook2005-3-to-zedai.xpl:226:44:Normalize mixed section and block content model for level1   @o.d.c.x.c.i.slf4jXProcMessageListener:80#info
INFO   [     com.xmlcalabash.runtime.XAtomicStep] bundle://108.0:1/xml/dtbook2005-3-to-zedai.xpl:226:44:Normalize mixed section and block content model for level1   @o.d.c.x.c.i.slf4jXProcMessageListener:80#info
INFO   [     com.xmlcalabash.runtime.XAtomicStep] bundle://108.0:1/xml/dtbook2005-3-to-zedai.xpl:226:44:Normalize mixed section and block content model for level2   @o.d.c.x.c.i.slf4jXProcMessageListener:80#info
INFO   [     com.xmlcalabash.runtime.XAtomicStep] bundle://108.0:1/xml/dtbook2005-3-to-zedai.xpl:226:44:Normalize mixed section and block content model for level2   @o.d.c.x.c.i.slf4jXProcMessageListener:80#info
INFO   [     com.xmlcalabash.runtime.XAtomicStep] bundle://108.0:1/xml/dtbook2005-3-to-zedai.xpl:226:44:Normalize mixed section and block content model for level2   @o.d.c.x.c.i.slf4jXProcMessageListener:80#info
INFO   [     com.xmlcalabash.runtime.XAtomicStep] bundle://108.0:1/xml/dtbook2005-3-to-zedai.xpl:226:44:Normalize mixed section and block content model for level2   @o.d.c.x.c.i.slf4jXProcMessageListener:80#info
INFO   [     com.xmlcalabash.runtime.XAtomicStep] bundle://108.0:1/xml/dtbook2005-3-to-zedai.xpl:226:44:Normalize mixed section and block content model for level2   @o.d.c.x.c.i.slf4jXProcMessageListener:80#info
INFO   [     com.xmlcalabash.runtime.XAtomicStep] bundle://108.0:1/xml/dtbook2005-3-to-zedai.xpl:237:39:Translate to ZedAI   @o.d.c.x.c.i.slf4jXProcMessageListener:80#info
INFO   [     com.xmlcalabash.runtime.XAtomicStep] bundle://108.0:1/xml/dtbook-to-zedai.convert.xpl:336:33:Generating CSS   @o.d.c.x.c.i.slf4jXProcMessageListener:80#info
INFO   [     o.d.c.x.c.steps.Message$MessageStep] bundle://136.0:1/xml/xproc/message.xpl:116:29:Input document is valid   @o.d.c.x.c.i.slf4jXProcMessageListener:80#info
INFO   [              org.daisy.pipeline.job.Job] Changing job status to: ERROR   @org.daisy.pipeline.job.Job:182#changeStatus
INFO   [o.d.p.persistence.impl.job.PersistentJob] Changing Status:ERROR   @o.d.p.p.impl.job.PersistentJob:156#onStatusChanged
CHANGING STATUS IN THE DB BEFORE POSTING IT!
WARN   [ org.eclipse.persistence.logging.default] Thread(Thread[Thread-69,5,Configuration Admin Service])--   @o.d.p.p.logging.Slf4jSessionLogger:114#log
ERROR  [    c.g.common.eventbus.EventBus.default] Could not dispatch event: org.daisy.common.messaging.Message@48f95d11 to handler [wrapper public synchronized void org.daisy.pipeline.persistence.impl.messaging.PersistentMessageEventListener.handleMessage(org.daisy.common.messaging.Message)]   @com.google.common.eventbus.EventBus:316#dispatch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74) ~[na:na]
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47) ~[na:na]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314) ~[na:na]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296) ~[na:na]
	at com.google.common.eventbus.EventBus.post(EventBus.java:267) ~[na:na]
	at org.daisy.pipeline.job.Job.broadcastError(Job.java:199) ~[na:na]
	at org.daisy.pipeline.job.Job.run(Job.java:226) ~[na:na]
	at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:113) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
Caused by: javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.3.2.v20111125-r10461): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL170830103847100' defined on 'PERSISTENTMESSAGE'.
Error Code: 20000
Call: INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
Query: InsertObjectQuery(org.daisy.pipeline.persistence.impl.messaging.PersistentMessage@59eada4f)
	at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commitInternal(EntityTransactionImpl.java:102) ~[na:na]
	at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:63) ~[na:na]
	at org.daisy.pipeline.persistence.impl.Database.addObject(Database.java:24) ~[na:na]
	at org.daisy.pipeline.persistence.impl.messaging.PersistentMessageEventListener.handleMessage(PersistentMessageEventListener.java:34) ~[na:na]
	... 12 common frames omitted
Caused by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL170830103847100' defined on 'PERSISTENTMESSAGE'.
Error Code: 20000
Call: INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
Query: InsertObjectQuery(org.daisy.pipeline.persistence.impl.messaging.PersistentMessage@59eada4f)
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[na:na]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:840) ~[na:na]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:906) ~[na:na]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:592) ~[na:na]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:535) ~[na:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1717) ~[na:na]
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:253) ~[na:na]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:207) ~[na:na]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:193) ~[na:na]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java:342) ~[na:na]
	at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:162) ~[na:na]
	at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:177) ~[na:na]
	at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:472) ~[na:na]
	at org.eclipse.persistence.queries.InsertObjectQuery.executeCommit(InsertObjectQuery.java:80) ~[na:na]
	at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:90) ~[na:na]
	at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:287) ~[na:na]
	at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:58) ~[na:na]
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:844) ~[na:na]
	at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:743) ~[na:na]
	at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108) ~[na:na]
	at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85) ~[na:na]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2871) ~[na:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1516) ~[na:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1498) ~[na:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1449) ~[na:na]
	at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjectsForClassWithChangeSet(CommitManager.java:224) ~[na:na]
	at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:123) ~[na:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:3799) ~[na:na]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1415) ~[na:na]
	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitToDatabase(RepeatableWriteUnitOfWork.java:636) ~[na:na]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1505) ~[na:na]
	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:267) ~[na:na]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1143) ~[na:na]
	at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commitInternal(EntityTransactionImpl.java:84) ~[na:na]
	... 15 common frames omitted
Caused by: java.sql.SQLIntegrityConstraintViolationException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL170830103847100' defined on 'PERSISTENTMESSAGE'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[na:na]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[na:na]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[na:na]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[na:na]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[na:na]
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) ~[na:na]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[na:na]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[na:na]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[na:na]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:831) ~[na:na]
	... 47 common frames omitted
Caused by: org.apache.derby.impl.jdbc.EmbedSQLException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL170830103847100' defined on 'PERSISTENTMESSAGE'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) ~[na:na]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source) ~[na:na]
	... 57 common frames omitted
Caused by: org.apache.derby.iapi.error.StandardException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL170830103847100' defined on 'PERSISTENTMESSAGE'.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source) ~[na:na]
	at org.apache.derby.impl.sql.execute.IndexChanger.insertAndCheckDups(Unknown Source) ~[na:na]
	at org.apache.derby.impl.sql.execute.IndexChanger.doInsert(Unknown Source) ~[na:na]
	at org.apache.derby.impl.sql.execute.IndexChanger.insert(Unknown Source) ~[na:na]
	at org.apache.derby.impl.sql.execute.IndexSetChanger.insert(Unknown Source) ~[na:na]
	at org.apache.derby.impl.sql.execute.RowChangerImpl.insertRow(Unknown Source) ~[na:na]
	at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source) ~[na:na]
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source) ~[na:na]
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source) ~[na:na]
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source) ~[na:na]
	... 51 common frames omitted
ERROR  [              org.daisy.pipeline.job.Job] job finished with error state   @org.daisy.pipeline.job.Job:227#run
java.lang.NullPointerException: null
	at com.xmlcalabash.core.XProcRuntime.close(XProcRuntime.java:344) ~[na:na]
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:252) ~[na:na]
	at org.daisy.pipeline.job.Job.run(Job.java:216) ~[na:na]
	at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:113) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
INFO  FINALIZE_SESSION [ o.d.p.j.impl.DefaultJobExecutionService] Stopping logging to job's log file   @o.d.p.j.i.DefaultJobExecutionService$1:114#run
INFO   [        org.restlet.Component.LogService] 2017-08-30	11:06:10	192.168.137.10	-	192.168.137.3	8181	GET	/ws/jobs/b8e0dcd5-d8f1-4a1d-a810-bb56f0cc41e5	msgSeq=100000	200	-	0	4http://qa-pipeline2:8181	Apache-HttpClient/4.5.3 (Java/1.8.0_131)	-   @org.restlet.engine.log.LogFilter:106#afterHandle
INFO   [        org.restlet.Component.LogService] 2017-08-30	11:06:10	192.168.137.10	-	192.168.137.3	8181	GET	/ws/jobs/b8e0dcd5-d8f1-4a1d-a810-bb56f0cc41e5/log	-	200	24326	0	1http://qa-pipeline2:8181	Apache-HttpClient/4.5.3 (Java/1.8.0_131)	-   @org.restlet.engine.log.LogFilter:106#afterHandle
INFO   [        org.restlet.Component.LogService] 2017-08-30	11:06:24	192.168.137.1	-	192.168.137.3	8181	HEAD	/ws/jobs	-	200	0	-	9	http://localhost:8181	Monit/5.20.0	-   @org.restlet.engine.log.LogFilter:106#afterHandle
INFO   [        org.restlet.Component.LogService] 2017-08-30	11:07:54	192.168.137.1	-	192.168.137.3	8181	HEAD	/ws/jobs	-	200	0	-	13	http://localhost:8181	Monit/5.20.0	-   @org.restlet.engine.log.LogFilter:106#afterHandle

```

**Comment by bertfrees** [comment]
The SQL error is most likely not the cause of the job failure. This might be the same issue as someone reported earlier, and for which we are going to do a bugfix release. I suggest you try again after updating, and then we can look into it further if needed.

**Comment by bertfrees** [comment]
@rkeiii The bugfix release v1.10.3 is ready: see http://daisy.github.io/pipeline/Download.html

**Comment by rkeiii** [comment]
@bertfrees It looks like when 1.10.3 got released it didn't get binaries, just src instead? I would normally expect this link to work but it does not.

https://github.com/daisy/pipeline-assembly/releases/download/v1.10.3/pipeline2-1.10.3_linux.zip

Here's the link we used to download 1.10.2.
https://github.com/daisy/pipeline-assembly/releases/download/v1.10.2/pipeline2-1.10.2_linux.zip

**Comment by bertfrees** [comment]
Indeed it has no download link. You have to use the updater tool. Here is a howto: http://daisy.github.io/pipeline/Get-Help/User-Guide/Installation/#updater.

**Comment by rkeiii** [comment]
Sadly I don't think we can work with that. Our process bakes the pipeline installation into a Docker image. So without doing anything too hacky we really do need binaries we can simply decompress during the Docker image building process. Or I suppose we could start building it form source ourselves but I'd really rather not.

We have always relied on these "linux" releases. Are these being dropped from the project going forward?

**Comment by bertfrees** [comment]
No but we plan to more regularly make "in-between" releases and we chose to do it without uploading the binaries because it takes less time. The major releases will still include all the packages for all platforms.

But if it's really a stumbling block I'm happy to upload the Linux ZIP on special request.

By the way building releases from source is really easy. Maven should be all that is required to build a ZIP. You should consider it.

**Comment by rkeiii** [comment]
@bertfrees If you wouldn't mind I would appreciate it if you could push up the Linux binaries for this release 1.10.3.

I agree that you folks have a pretty straightforward and well documented build process. I will raise this issue with our internal team and see about coming up with a path forward for future releases.

**Comment by rkeiii** [comment]
Just wanted to note I built 1.10.3 and it did resolve our problems. I was able to successfully convert a document.

**Comment by bertfrees** [comment]
https://github.com/daisy/pipeline-assembly/releases/tag/v1.10.3
