### ISSUE TITLE
WebUI fails on start (Linux) java.sql.SQLSyntaxErrorException: Table/View 'PLAY_EVOLUTIONS' does not exist.

### ISSUE THREAD

**Issue by VK2BEA** [daisy/pipeline#547]
The WebUI is failing with the following message.  Does anyone know how to fix this ? (Linux platform)

Michael

```
[industrynumbers webui] $ JAVA=/etc/alternatives/jre_1.8.0_openjdk/bin/java JAVA_HOME=/etc/alternatives/jre_1.8.0_openjdk/ TERM=xterm-color ./activator run
[info] Loading project definition from /home/michael/DAISYpipeline/pipeline/webui/project
[info] Updating {file:/home/michael/DAISYpipeline/pipeline/webui/project/}webui-build...
[warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
[warn]  * com.typesafe.sbt:sbt-native-packager:(1.0.6, 1.1.0-RC2)
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to webui (in build file:/home/michael/DAISYpipeline/pipeline/webui/)
[info] Updating {file:/home/michael/DAISYpipeline/pipeline/webui/}root...
[info] Resolving net.contentobjects.jnotify#jnotify;0.94-play-1 ...
[info] Done updating.

--- (Running the application, auto-reloading is enabled) ---

[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 42 Scala sources and 31 Java sources to /home/michael/DAISYpipeline/pipeline/webui/target/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.6. Compiling...
[info]   Compilation completed in 6.943 s
[info] /home/michael/DAISYpipeline/pipeline/webui/app/controllers/Account.java: /home/michael/DAISYpipeline/pipeline/webui/app/controllers/Account.java uses or overrides a deprecated API.
[info] /home/michael/DAISYpipeline/pipeline/webui/app/controllers/Account.java: Recompile with -Xlint:deprecation for details.
[info] LESS compiling on 1 source(s)
[info] application - Creating Pool for datasource 'default'
[warn] c.z.h.u.DriverDataSource - Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.
[info] p.a.d.DefaultDBApi - Database [default] connected at jdbc:derby:dp2webui
[warn] p.a.d.e.DefaultEvolutionsApi - could not create play_evolutions table
java.sql.SQLSyntaxErrorException: TYPE 'TEXT' does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at com.zaxxer.hikari.proxy.StatementProxy.execute(StatementProxy.java:83) ~[HikariCP-2.3.7.jar:na]
	at com.zaxxer.hikari.proxy.StatementJavassistProxy.execute(StatementJavassistProxy.java) ~[HikariCP-2.3.7.jar:na]
Caused by: org.apache.derby.iapi.error.StandardException: TYPE 'TEXT' does not exist.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.sql.compile.QueryTreeNode.bindUserType(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.sql.compile.ColumnDefinitionNode.checkUserType(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.sql.compile.TableElementList.validate(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.sql.compile.CreateTableNode.bindStatement(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source) ~[derby-10.11.1.1.jar:na]
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source) ~[derby-10.11.1.1.jar:na]
[error] application - 
! @7dk72eip5 - Internal server error, for (GET) [/] ->
 
play.api.UnexpectedException: Unexpected exception[SQLSyntaxErrorException: Table/View 'PLAY_EVOLUTIONS' does not exist.]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:165) ~[play-server_2.11-2.4.1.jar:2.4.1]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.1.jar:2.4.1]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.1.jar:2.4.1]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.1.jar:2.4.1]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.6.jar:na]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.1.jar:2.4.1]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111) ~[play-server_2.11-2.4.1.jar:2.4.1]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.6.jar:na]
Caused by: java.sql.SQLSyntaxErrorException: Table/View 'PLAY_EVOLUTIONS' does not exist.

```

**Comment by bertfrees** [comment]
@josteinaj Does this ring a bell?

**Comment by josteinaj** [comment]
Hi @VK2BEA. From what I can tell, you're running the WebUI straight from the git repository?

The Play Framework is for some reason not able to create the PLAY_EVOLUTIONS table by itself, so I've prepared an empty database with only that table in it, stored in the "dp2webui-cleandb" folder. When you start the WebUI, it uses the "dp2webui" folder.

Could you try deleting the "dp2webui" folder (if there is one), and making a copy of "dp2webui-cleandb", naming the copy "dp2webui"?

73 de LA7WOA

**Comment by VK2BEA** [comment]
Yes, that fixed it. Curious, because I had run the webUI a few months ago and didn't encounter this problem. Maybe the 'Play Framework' was updated in the mean time.
Thanks.
  Michael (NV3Z / VK2BEA / G4NYV 8-)

**Comment by josteinaj** [comment]
Glad I could help
