### ISSUE TITLE
UnsupportedOperationException occuring in v1.14.3, probably in fileset-utils

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#640]
I'm trying to upgrade the [nordic migrator](https://github.com/nlbdev/nordic-epub3-dtbook-migrator) from using modules-parent:1.14.2 to modules-parent:1.14.3. I'm getting the same error with newer versions of modules-parent as well.

I was not aware of any breaking change, but there seems to be some. For instance, I found that `px:fileset-join` has changed the name of its output port from `fileset.out` to `result`. This was not too much of a problem to fix, since the error message said that there was no port with such a name, and by looking at [the diff between v1.14.2 and v1.14.3 in pipeline-modules](https://github.com/daisy/pipeline-modules/compare/v1.14.2...v1.14.3) I found that the new name was `result`.

The error I'm getting now just throws a stacktrace:

```
java.lang.RuntimeException: java.lang.UnsupportedOperationException: Unexpected node type
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:264)
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:200)
	at org.daisy.maven.xproc.pipeline.DaisyPipeline2.run(DaisyPipeline2.java:119)
	at org.daisy.maven.xproc.xprocspec.XProcSpecRunner.run(XProcSpecRunner.java:204)
	at org.daisy.maven.xproc.xprocspec.XProcSpecRunner.run(XProcSpecRunner.java:334)
	at org.daisy.maven.xproc.xprocspec.XProcSpecRunner.run(XProcSpecRunner.java:342)
	at org.daisy.pipeline.junit.AbstractXSpecAndXProcSpecTest.runXProcSpec(AbstractXSpecAndXProcSpecTest.java:68)
	at org.daisy.pipeline.junit.AbstractXSpecAndXProcSpecTest.runXSpecAndXProcSpec(AbstractXSpecAndXProcSpecTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.daisy.pipeline.junit.OSGiLessRunner$1.evaluate(OSGiLessRunner.java:71)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.daisy.pipeline.junit.TestRunner.runChild(TestRunner.java:55)
	at org.daisy.pipeline.junit.TestRunner.runChild(TestRunner.java:22)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.UnsupportedOperationException: Unexpected node type
	at com.xmlcalabash.util.TreeWriter.addSubtree(TreeWriter.java:165)
	at com.xmlcalabash.library.Parameters.run(Parameters.java:143)
	at com.xmlcalabash.library.InScopeNames.run(InScopeNames.java:58)
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:399)
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:263)
	at com.xmlcalabash.runtime.XGroup.run(XGroup.java:27)
	at com.xmlcalabash.runtime.XForEach.run(XForEach.java:127)
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:268)
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:148)
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:108)
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:263)
	at com.xmlcalabash.runtime.XWhen.run(XWhen.java:75)
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:142)
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:263)
	at com.xmlcalabash.runtime.XWhen.run(XWhen.java:75)
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:142)
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:268)
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:148)
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:108)
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:263)
	at com.xmlcalabash.runtime.XGroup.run(XGroup.java:32)
	at com.xmlcalabash.runtime.XTry.run(XTry.java:99)
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:268)
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:148)
	at com.xmlcalabash.extensions.Eval.run(Eval.java:249)
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:399)
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:263)
	at com.xmlcalabash.runtime.XGroup.run(XGroup.java:32)
	at com.xmlcalabash.runtime.XTry.run(XTry.java:99)
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:263)
	at com.xmlcalabash.runtime.XOtherwise.run(XOtherwise.java:27)
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:142)
	at com.xmlcalabash.runtime.XForEach.run(XForEach.java:127)
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:268)
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:148)
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:108)
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:268)
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:148)
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:258)
	... 39 more
```

Judging by the stacktrace, I suspect that it's got to do with `px:fileset-load` and/or `px:fileset-add-entry`, and the commit https://github.com/daisy/pipeline-modules/commit/9bf329bf52270d5a40c765d9c2b321a3cb3b7c8c, which seems to add some form of type checking.

I also suspect that this is the relevant place in the nordic migrator where `px:fileset-load` is invoked:
https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/fb4949e9e963e6f29250dea6225b5985a0967bb9/src/main/resources/xml/xproc/step/2015-1/html-validate.step.xpl#L80-L87

However, I don't see anything out of the ordinary there, so I'm not sure where to go from here.

The nordic migrator seems to work fine when built using `modules-parent:1.14.2`, and then inserted into a 1.14.3 engine, so it might be that this is only related to testing. So maybe xprocspec has something to do with this?

### Steps to Reproduce

```bash
git clone https://github.com/nlbdev/nordic-epub3-dtbook-migrator.git
cd nordic-epub3-dtbook-migrator
git checkout modules-parent-1.14.3
```

To limit the amount of output, add ` focus=""` to the `x:description` element in `src/test/xprocspec/2015-1/html-validate.step.xprocspec`.

```bash
mvn clean test
```

### Environment

* Operating system: Ubuntu 22.04
* DAISY Pipeline 2 version: 1.14.3
* Interface: Maven

**Comment by bertfrees** [comment]
Hi @josteinaj.

The issue seems to have to do with a `p:in-scope-names`. It's probably related to https://github.com/daisy/pipeline-modules/commit/9bf329bf52270d5a40c765d9c2b321a3cb3b7c8c indeed. This commit is not really about type checking but about allowing XProc variables/options to have any XDM value. In this case I think `p:in-scope-names` is trying to create a string from a variable with a value of type `attribute()` (to include in the `c:param-set` document). I've seen this issue before. The solution will probably involve adding a `string(...)` call somewhere or an implicit cast using a `cx:as` attribute (either in your code or in an XProc step of Pipeline), or a fix to the `p:in-scope-names` step.

But I would like to urge you to upgrade straight to the latest version of modules-parent, that is 1.14.7, not 1.14.3. Because it's hard for me to keep supporting old versions. This might be an issue that I have fixed a while ago (and maybe have already forgotten about).

Regarding the breaking change: there are breaking changes all the time unfortunately, and there are probably more to come. I know this makes it hard to use Pipeline as an XProc library, but the changes are absolutely necessary to make the code maintainable. The unfortunate truth is that Pipeline is simply not mature enough yet to be used as a (stable) XProc library (and maybe was never meant to be).

Maybe [this page](http://daisy.github.io/pipeline/api/org/daisy/pipeline/modules/fileset-utils/library.xpl.html) can also help you when you're upgrading and run into issues?

**Comment by josteinaj** [comment]
> But I would like to urge you to upgrade straight to the latest version of modules-parent, that is 1.14.7, not 1.14.3.

Good point. I was upgrading one version at a time, thinking that would make it easier to upgrade for me. But yes, I'll just jump straight to 1.14.7 instead.

> Maybe [this page](http://daisy.github.io/pipeline/api/org/daisy/pipeline/modules/fileset-utils/library.xpl.html) can also help you when you're upgrading and run into issues?

That's useful, thanks!

> The solution will probably involve adding a `string(...)` call somewhere or an implicit cast using a `cx:as` attribute (either in your code or in an XProc step of Pipeline), or a fix to the `p:in-scope-names` step.

Yes, I was thinking I could add a `string(…)` somewhere as well but I had no idea where. But since you point to `p:in-scope-names` then I think this one is the only possibility, so I'll look into this one:
https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/fb4949e9e963e6f29250dea6225b5985a0967bb9/src/main/resources/xml/xproc/step/check-image-file-signatures.xpl#L38

I'll let you know here how it goes, thanks :+1:

**Comment by josteinaj** [comment]
Yup, simple as that:

https://github.com/nlbdev/nordic-epub3-dtbook-migrator/commit/3310bf16330e5ca732f04a66b8f5388385752c74

Thanks for pointing me in the right direction!

**Comment by bertfrees** [comment]
Cool!
